import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginButton from "./LoginButton";
import { getServerSession } from "next-auth";
import LogoutButton from "./LogoutButton";
import { authOptions } from "../pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  console.log(session);

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav id="top-nav">
          <p>Forum</p>
          <Link href="/">Home</Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          <Link href="/register">SignUp</Link>
          { session ? <LogoutButton /> : <LoginButton /> }
        </nav>
        {children}
      </body>
    </html>
  );
}
